version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo "Preparing Apache Maven for build"
      - chmod +x ./mvnw
      - echo "Logging in to AWS ECR"
      - |
        AWS_REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
          docker login --username AWS --password-stdin ${AWS_REPO_URL}

  build:
    commands:
      - echo "Build with Apache Maven"
      - ./mvnw clean package
      - echo "Building Docker images"
      - |
        docker build -f ./bin/Dockerfile \
          --build-arg TARGET_FOLDER=./service-exam-aggregator/target \
          -t ${AWS_REPO_URL}/service-exam-aggregator:latest \
          -t aggregator:latest .
      - |
        docker build -f ./bin/Dockerfile \
          --build-arg TARGET_FOLDER=./service-provider-history/target \
          -t ${AWS_REPO_URL}/service-provider-history:latest \
          -t provider-history:latest .
      - |
        docker build -f ./bin/Dockerfile \
          --build-arg TARGET_FOLDER=./service-provider-math/target \
          -t ${AWS_REPO_URL}/service-provider-math:latest \
          -t provider-math:latest .

  post_build:
    commands:
      - echo Pushing Docker images to ECR
      - docker push ${AWS_REPO_URL}/service-exam-aggregator:latest
      - docker push ${AWS_REPO_URL}/service-provider-history:latest
      - docker push ${AWS_REPO_URL}/service-provider-math:latest