apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: training-demo
spec:
  selector:
    name: aggregator
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080