apiVersion: v1
kind: Service
metadata:
  name: provider-history-service
  namespace: training-demo
spec:
  selector:
    name: provider-history
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: provider-math-service
  namespace: training-demo
spec:
  selector:
    name: provider-math
  ports:
    - port: 8080
      targetPort: 8080