aggregator:
  correct-moon-phase: true
  providers:
    - name: math
      endpoint: http://localhost:8081/
    - name: history
      endpoint: http://localhost:8082/

management:
  endpoint:
    health:
      show-details: always